=== dexwerx/interpss/trunk/ieee.odm_pss/schema/ODM_StudyCase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.ieee.org/cmte/psace/oss/odm/pss/Schema/v1"
	xmlns:pss="http://www.ieee.org/cmte/psace/oss/odm/pss/Schema/v1"
	elementFormDefault="qualified">

    <annotation>
    	<documentation>Copyright www.interpss.org 2008</documentation>
    </annotation>
    <include schemaLocation="ODM_DataType.xsd"></include>
    <include schemaLocation="ODM_DynamicDataType.xsd"></include>

	<element name="PSSStudyCase" type="pss:StudyCaseXmlType"></element>
	<complexType name="StudyCaseXmlType">
		<complexContent>
			<extension base="pss:IDRecordXmlType">
				<sequence>
					<element name="schemaVersion" minOccurs="1"
						maxOccurs="1">
						<simpleType>
							<restriction base="string">
								<enumeration value="V1.00"></enumeration>
								<enumeration value="V1.00.DEV"></enumeration>
							</restriction>
						</simpleType>
					</element>
					<element name="originalFormat" minOccurs="1"
						maxOccurs="1">
						<simpleType>
							<restriction base="string">
								<enumeration value="IEEE-CDF"></enumeration>
								<enumeration value="PSS-E"></enumeration>
								<enumeration value="UCTE-DEF"></enumeration>
								<enumeration value="InterPSS"></enumeration>
								<enumeration value="PSAT"></enumeration>
								<enumeration value="BPA"></enumeration>
								<enumeration value="IEEE-ODM-PSS"></enumeration>
								<enumeration value="Custom"></enumeration>
							</restriction>
						</simpleType>
					</element>
					<element name="adapterProviderName" type="string"
						minOccurs="0" maxOccurs="1">
					</element>
					<element name="adapterProviderVersion" type="string"
						minOccurs="0" maxOccurs="1">
					</element>
					<element name="analysisCategory" minOccurs="1"
						maxOccurs="1">
						<simpleType>
							<restriction base="string">
								<enumeration value="Loadflow"></enumeration>
								<enumeration value="ShortCircuit"></enumeration>
								<enumeration
									value="TransientStability">
								</enumeration>
							</restriction>
						</simpleType>
					</element>
					<element name="networkCategory" minOccurs="1"
						maxOccurs="1">
						<simpleType>
							<restriction base="string">
								<enumeration value="Transmission"></enumeration>
								<enumeration value="Distribution"></enumeration>
							</restriction>
						</simpleType>
					</element>
					<element name="baseCase"
						type="pss:PSSNetworkXmlType" minOccurs="1" maxOccurs="1">
					</element>
					<element name="modificationList"
						type="pss:ModifyRecordListXmlType" minOccurs="0" maxOccurs="1">
					</element>
					<element name="scenarioList"
						type="pss:ScenarioListXmlType" minOccurs="0" maxOccurs="1">
					</element>
					<element name="dynamicDataList" type="string" maxOccurs="1" minOccurs="0"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="PSSNetworkXmlType">
		<complexContent>
			<extension base="pss:IDRecordXmlType">
				<sequence>
					<element name="basePower" type="double"
						minOccurs="1" maxOccurs="1">
					</element>
					<element name="basePowerUnit" minOccurs="1"
						maxOccurs="1">
						<simpleType>
							<restriction base="string">
								<enumeration value="KVA"></enumeration>
								<enumeration value="MVA"></enumeration>
							</restriction>
						</simpleType>
					</element>
					<element name="busList"
						type="pss:BusRecordListXmlType" minOccurs="1" maxOccurs="1">
					</element>
					<element name="branchList"
						type="pss:BranchRecordListXmlType" minOccurs="1" maxOccurs="1">
					</element>
					<element name="lossZoneList" minOccurs="0" type="pss:lossZoneListComplexType">
					</element>
					<element name="interchangeList" minOccurs="0">
						<complexType>
							<sequence>
								<element name="interchange"
									minOccurs="0" maxOccurs="unbounded" type="pss:interchangeComplexType">
								</element>
							</sequence>
						</complexType>
					</element>
					<element name="tieLineList" minOccurs="0">
						<complexType>
							<sequence>
								<element name="tieline" minOccurs="0"
									maxOccurs="unbounded">
									<complexType>
										<sequence>
											<element name="meteredBus"
												type="pss:IDRefRecordXmlType" minOccurs="1">
											</element>
											<element
												name="meteredAreaNumber" type="int" minOccurs="1">
											</element>
											<element
												name="nonMeteredBus" type="pss:IDRefRecordXmlType"
												minOccurs="1">
											</element>
											<element
												name="nonMeteredAreaNumber" type="int" minOccurs="1">
											</element>
											<element name="cirId"
												type="string" maxOccurs="1" minOccurs="1">
											</element>
										</sequence>
									</complexType>
								</element>
							</sequence>
						</complexType>
					</element>
					<element name="dcLineList" type="pss:DCLineListXmlType" maxOccurs="1" minOccurs="0"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="ModifyRecordListXmlType">
		<sequence>
			<element name="modifyRec" type="pss:ModifyRecordXmlType" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="ModifyRecordXmlType">
		<complexContent>
			<extension base="pss:IDRecordXmlType"></extension>
		</complexContent>
	</complexType>
	
    <complexType name="ScenarioListXmlType">
    	<sequence>
    		<element name="scenario" type="pss:ScenarioXmlType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    <complexType name="ScenarioXmlType">
    	<complexContent>
    		<extension base="pss:IDRecordXmlType">
    			<sequence>
    				<element name="modifcationList"
    					type="pss:ModifyRecordListXmlType" minOccurs="0"
    					maxOccurs="1">
    				</element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>


    <complexType name="DynamicDataListXmlType">
    	<sequence>
    		<element name="busDynDataList"
    			type="pss:BusDynDataListXmlType" maxOccurs="1" minOccurs="0">
    		</element>
    		<element name="branchDynDataList" type="pss:BranchDynDataListXmlType" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>
    <complexType name="lossZoneListComplexType">
    	<sequence>
    		<element minOccurs="0" maxOccurs="unbounded"
    			name="lossZone">
    			<complexType>
    				<sequence>
    					<element minOccurs="0" name="zoneNumber"
    						type="int" maxOccurs="1">
    					</element>
    					<element minOccurs="0" name="zoneName"
    						type="string">
    					</element>
    				</sequence>
    			</complexType>
    		</element>
    	</sequence>
    </complexType>
    <complexType name="interchangeComplexType">
    	<sequence>
    		<element minOccurs="0" name="ieeeCDFInterchange" type="pss:ieeeCDFInterchangeComplexType">
    		</element>
    		<element minOccurs="0" name="ucteExchange">
    			<complexType>
    				<sequence>
    					<element minOccurs="1" name="fromIsoId"
    						type="string">
    					</element>
    					<element minOccurs="1" name="toIsoId"
    						type="string">
    					</element>
    					<element minOccurs="1" name="exchangePower"
    						type="pss:PowerXmlType">
    					</element>
    					<element minOccurs="0" name="comment"
    						type="string">
    					</element>
    				</sequence>
    			</complexType>
    		</element>
    		<element minOccurs="0" maxOccurs="1"
    			name="bpaInterchange">
    			<complexType>
    				<sequence>
    					<element minOccurs="1" maxOccurs="1"
    						name="areaName" type="string">
    					</element>
    					<element minOccurs="0" maxOccurs="1"
    						name="swingBusId" type="pss:IDRefRecordXmlType">
    					</element>
    					<element minOccurs="0" maxOccurs="1"
    						name="ratedVoltage" type="pss:VoltageXmlType">
    					</element>
    					<element minOccurs="1" maxOccurs="1"
    						name="interchangePower">
    						<complexType>
    							<sequence>
    								<element minOccurs="0" maxOccurs="1"
    									name="overall" type="pss:PowerXmlType">
    								</element>
    								<element minOccurs="0"
    									maxOccurs="unbounded" name="Tielines">
    									<complexType>
    										<sequence>
    											<element minOccurs="1"
    												maxOccurs="1" name="toArea" type="string">
    											</element>
    											<element minOccurs="1"
    												maxOccurs="1" name="transferedPower"
    												type="pss:PowerXmlType">
    											</element>
    										</sequence>
    									</complexType>
    								</element>
    							</sequence>
    						</complexType>
    					</element>
    					<element minOccurs="0" maxOccurs="1"
    						name="zoneWithinAreaList"
    						type="pss:lossZoneListComplexType">
    					</element>
    					<element minOccurs="0" maxOccurs="1"
    						name="measuredOnFromSide" type="boolean">
    					</element>
    				</sequence>
    			</complexType>
    		</element>
    	</sequence>
    </complexType>
    <complexType name="ieeeCDFInterchangeComplexType">
    	<sequence>
    		<element minOccurs="1" name="areaNumber" type="int"></element>
    		<element minOccurs="1" name="swingBus"
    			type="pss:IDRefRecordXmlType">
    		</element>
    		<element minOccurs="1" name="alternateSwingBusName"
    			type="string">
    		</element>
    		<element minOccurs="1" name="interchangePower"
    			type="pss:PowerXmlType">
    		</element>
    		<element minOccurs="1" name="interchangeErrTolerance"
    			type="double">
    		</element>
    		<element minOccurs="0" name="areaCode" type="string"></element>
    		<element minOccurs="0" name="areaName" type="string"></element>
    		<element minOccurs="0" maxOccurs="1"
    			name="zoneListWithinArea" type="pss:lossZoneListComplexType">
    		</element>
    		<element minOccurs="0" maxOccurs="1"
    			name="measuredOnFromSide" type="boolean">
    		</element>
    	</sequence>
    </complexType>
</schema>

=== dexwerx/interpss/trunk/ieee.odm_pss/junk/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<pss:PSSStudyCase id="idvalue0" xmlns:pss="http://www.ieee.org/odm/Schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ieee.org/odm/Schema ../schema/ODM_StudyCase.xsd ">
  <pss:schemaVersion>V0.7</pss:schemaVersion>
  <pss:baseCase id="idvalue1">
    <pss:networkCategory>Transmission</pss:networkCategory>
    <pss:analysisCategory>Loadflow</pss:analysisCategory>
    <pss:basePower unit="PU" value="0.0"/>
    <pss:busList>
    	<pss:bus1 xsi:type="LoadflowBusXmlType" id="BusId">
    		<pss:baseVoltage unit="PU" value="0.0" />
    	</pss:bus1>
    </pss:busList>
    <pss:branchList/>
  </pss:baseCase>
</pss:PSSStudyCase>

=== dexwerx/interpss/branches/ieee.odm.test_07242010/testdata/ieee_odm/tempate.xml
<?xml version="1.0" encoding="UTF-8"?>
<pss:PSSStudyCase id="studyCaseId" 
	xmlns:pss="http://www.ieee.org/odm/Schema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.ieee.org/odm/Schema ../../schema/ODM_StudyCase.xsd ">
  <pss:schemaVersion>V0.7</pss:schemaVersion>
  <pss:contentInfo>
    <pss:originalDataFormat>Custom</pss:originalDataFormat>
    <pss:adapterProviderName>www.interpss.org</pss:adapterProviderName>
    <pss:adapterProviderVersion>1.00</pss:adapterProviderVersion>
  </pss:contentInfo>  
  <pss:baseCase id="baseCaseId">
    <pss:networkCategory>Transmission</pss:networkCategory>
    <pss:analysisCategory>Loadflow</pss:analysisCategory>
    <pss:basePower unit="MVA" value="100.0"/>
    <pss:busList/>
    <pss:branchList/>
  </pss:baseCase>
</pss:PSSStudyCase>
